# Generated by Django 4.1.6 on 2023-02-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apitest2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiTest2',
        ),
    ]
