# Generated by Django 4.2 on 2023-04-12 18:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistQuestionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=256)),
                ('answer_type', models.CharField(choices=[('CB', 'Checkbox'), ('R5', '1-5'), ('RX', '1-10'), ('TX', 'Text'), ('WL', 'Wheel')], default='CB', max_length=2)),
                ('allow_notes', models.BooleanField(default=True)),
                ('answer_checkbox', models.BooleanField(default=None, null=True)),
                ('answer_radio_5', models.PositiveSmallIntegerField(default=None, null=True)),
                ('answer_radio_10', models.PositiveSmallIntegerField(default=None, null=True)),
                ('answer_text', models.TextField(default=None, null=True)),
                ('answer_wheel', models.CharField(default=None, max_length=16, null=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistQuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=256)),
                ('answer_type', models.CharField(choices=[('CB', 'Checkbox'), ('R5', '1-5'), ('RX', '1-10'), ('TX', 'Text'), ('WL', 'Wheel')], default='CB', max_length=2)),
                ('allow_notes', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(default='', max_length=128)),
                ('text', models.TextField(default='')),
                ('max_mileage', models.PositiveIntegerField(null=True)),
                ('curr_mileage', models.PositiveIntegerField(default=0)),
                ('max_time', models.DurationField(null=True)),
                ('curr_time', models.DurationField(default=datetime.timedelta)),
                ('install_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(default='', max_length=128)),
                ('text', models.TextField(default='')),
                ('max_mileage', models.PositiveIntegerField(null=True)),
                ('curr_mileage', models.PositiveIntegerField(default=0)),
                ('max_time', models.DurationField(null=True)),
                ('curr_time', models.DurationField(default=datetime.timedelta)),
                ('install_date', models.DateField(default=django.utils.timezone.now)),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('refurbished', models.PositiveSmallIntegerField(default=0)),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('fuel', models.PositiveSmallIntegerField(default=0)),
                ('vehicle_type', models.CharField(choices=[('XX', 'Other'), ('MV', 'Mini van'), ('TK', 'Truck'), ('TR', 'Trailer'), ('PU', 'Pick-up truck')], default='XX', max_length=2)),
                ('drivetrain_type', models.CharField(choices=[('XXX', 'Other'), ('220', 'Two axles, both with two wheels'), ('240', 'Two axles, one with two whels, one with four'), ('222', 'Three axles with two wheels'), ('242', 'Three axles with two, three and two wheels'), ('244', 'Three axles, one with two wheels and two with three')], default='XXX', max_length=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='RepairWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField(default=None, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partwheel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField(default=None, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.part')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='partwheel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parttype'),
        ),
        migrations.AddField(
            model_name='part',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle'),
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('checklist_question_templates', models.ManyToManyField(blank=True, to='main.checklistquestiontemplate')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('checklist_question_instances', models.ManyToManyField(blank=True, to='main.checklistquestioninstance')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
