# Generated by Django 4.2.1 on 2024-01-11 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado en', models.DateTimeField(auto_now_add=True)),
                ('Actualizado en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado en', models.DateTimeField(auto_now_add=True)),
                ('Actualizado en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('profile_type', models.SmallIntegerField(choices=[('N', 'Not assigned'), ('D', 'Driver'), ('M', 'Mechanic'), ('A', 'Administrator'), ('S', 'Super user')], default='N')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado en', models.DateTimeField(auto_now_add=True)),
                ('Actualizado en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado en', models.DateTimeField(auto_now_add=True)),
                ('Actualizado en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=256, null=True)),
                ('Fecha último cambio', models.DateTimeField(blank=True)),
                ('Kilometraje último cambio', models.PositiveIntegerField(blank=True)),
                ('Funcionalidad de la parte', models.CharField(choices=[('OK', 'OK'), ('WR', 'Atención'), ('VB', 'Muy Mala'), ('NF', 'No Funciona')], default='OK', max_length=2)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'default_related_name': 'parts',
            },
        ),
        migrations.CreateModel(
            name='PartAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado en', models.DateTimeField(auto_now_add=True)),
                ('Actualizado en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado en', models.DateTimeField(auto_now_add=True)),
                ('Actualizado en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('formabs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.formabs')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m1', related_query_name='m2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': '%(class)s',
            },
            bases=('main.formabs',),
        ),
        migrations.CreateModel(
            name='PartTyreAbs',
            fields=[
                ('partabs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.partabs')),
                ('Frecuencia cambio tiempo', models.DurationField(blank=True, null=True)),
                ('Frecuencia cambio kilómetros', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('main.partabs',),
        ),
        migrations.CreateModel(
            name='PartWithLifespanAbs',
            fields=[
                ('partabs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.partabs')),
                ('Frecuencia cambio tiempo', models.DurationField(blank=True, null=True)),
                ('Frecuencia cambio kilómetros', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('main.partabs',),
        ),
        migrations.CreateModel(
            name='PartWithoutLifespanAbs',
            fields=[
                ('partabs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.partabs')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.partabs',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado en', models.DateTimeField(auto_now_add=True)),
                ('Actualizado en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('km', models.PositiveIntegerField(default=0)),
                ('fuel', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a1', related_query_name='a2', to='main.company')),
            ],
            options={
                'default_related_name': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='QuestionAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado en', models.DateTimeField(auto_now_add=True)),
                ('Actualizado en', models.DateTimeField(auto_now=True)),
                ('Título', models.CharField(max_length=128)),
                ('info', models.CharField(blank=True, max_length=256, null=True)),
                ('Tipo de pregunta', models.CharField(choices=[('D', 'Diaria'), ('M', 'Mantenimiento')], default='D', max_length=1)),
                ('Tipo de respuesta', models.CharField(choices=[('YN', 'Sí-No'), ('3S', 'Bueno-Regular-Malo'), ('NR', 'Número'), ('TX', 'Texto')], default='YN', max_length=2)),
                ('Permite observaciones', models.BooleanField(default=True)),
                ('form_abs', models.ManyToManyField(to='main.formabs')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o1', related_query_name='o2', to='main.partabs')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='n1', related_query_name='n2', to='main.questiongroup')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1', related_query_name='p2', to='main.vehicle')),
            ],
            options={
                'default_related_name': 'question_abs',
            },
        ),
        migrations.CreateModel(
            name='PartFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado en', models.DateTimeField(auto_now_add=True)),
                ('Actualizado en', models.DateTimeField(auto_now=True)),
                ('replaced', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=True)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('done_by', models.ForeignKey(limit_choices_to={'profile__position_type': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='h1', related_query_name='h2', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i1', related_query_name='i2', to='main.part')),
            ],
            options={
                'default_related_name': 'part_fixes',
            },
        ),
        migrations.CreateModel(
            name='PartChangeNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado en', models.DateTimeField(auto_now_add=True)),
                ('Actualizado en', models.DateTimeField(auto_now=True)),
                ('info', models.CharField(blank=True, max_length=1024, null=True)),
                ('urgency_type', models.CharField(choices=[('CR', 'Crítico'), ('IM', 'Importante'), ('EV', 'Eventual'), ('NO', 'Notificado')], default='NO', max_length=2)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f1', related_query_name='f2', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g1', related_query_name='g2', to='main.part')),
            ],
            options={
                'default_related_name': 'part_change_notices',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b1', related_query_name='b2', to='main.vehicle'),
        ),
        migrations.AddField(
            model_name='formabs',
            name='form_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='j1', related_query_name='j2', to='main.formgroup'),
        ),
        migrations.AddField(
            model_name='formabs',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k1', related_query_name='k2', to='main.vehicle'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionabs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.questionabs')),
                ('Respuesta Sí-No', models.BooleanField(blank=True, default=None, null=True)),
                ('Respuesta Bueno-Regular-Malo', models.CharField(blank=True, choices=[('G', 'Bueno'), ('R', 'Regular'), ('B', 'Malo')], default=None, max_length=1, null=True)),
                ('Respuesta Numérica', models.IntegerField(blank=True, null=True)),
                ('Respuesta de texto', models.CharField(blank=True, max_length=1024, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r1', related_query_name='r2', to='main.form')),
                ('question_abs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q1', related_query_name='q2', to='main.questionabs')),
            ],
            options={
                'default_related_name': 'questions',
            },
            bases=('main.questionabs',),
        ),
        migrations.CreateModel(
            name='PartWithoutLifespan',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.part')),
                ('abstract_part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='e1', related_query_name='e2', to='main.partwithoutlifespanabs')),
            ],
            options={
                'default_related_name': 'parts_without_lifespan',
            },
            bases=('main.part',),
        ),
        migrations.CreateModel(
            name='PartWithLifespan',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.part')),
                ('Frecuencia cambio tiempo', models.DurationField(blank=True, null=True)),
                ('Frecuencia cambio kilómetros', models.PositiveIntegerField(blank=True, null=True)),
                ('abstract_part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='c1', related_query_name='c2', to='main.partwithlifespanabs')),
            ],
            options={
                'default_related_name': 'parts_with_lifespan',
            },
            bases=('main.part',),
        ),
        migrations.CreateModel(
            name='PartTyre',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.part')),
                ('Frecuencia cambio tiempo', models.DurationField(blank=True, null=True)),
                ('Frecuencia cambio kilómetros', models.PositiveIntegerField(blank=True, null=True)),
                ('recaped', models.BooleanField(default=False)),
                ('abstract_part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='d1', related_query_name='d2', to='main.parttyreabs')),
            ],
            options={
                'default_related_name': 'parts_tyre',
            },
            bases=('main.part',),
        ),
        migrations.AddField(
            model_name='form',
            name='form_abs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l1', related_query_name='l2', to='main.formabs'),
        ),
    ]
