# Generated by Django 4.2.1 on 2024-01-16 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('profile_type', models.SmallIntegerField(choices=[('N', 'Not assigned'), ('D', 'Driver'), ('M', 'Mechanic'), ('A', 'Administrator'), ('S', 'Super user')], default='N')),
            ],
            options={
                'default_related_name': 'forms_abs',
            },
        ),
        migrations.CreateModel(
            name='FormGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartAbsProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PartTyreAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=128, null=True)),
                ('change_frequency_timedelta', models.DurationField(blank=True, default=None, null=True)),
                ('change_frequency_km', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'default_related_name': 'parts_tyre_abs',
            },
        ),
        migrations.CreateModel(
            name='PartWithLifespanAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=128, null=True)),
                ('change_frequency_timedelta', models.DurationField(blank=True, default=None, null=True)),
                ('change_frequency_km', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'default_related_name': 'parts_with_lifespan_abs',
            },
        ),
        migrations.CreateModel(
            name='PartWithoutLifespanAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'default_related_name': 'parts_without_lifespan_abs',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('formabs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.formabs')),
            ],
            options={
                'default_related_name': '%(class)s',
            },
            bases=('main.formabs',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=256, null=True)),
                ('km', models.PositiveIntegerField(default=0)),
                ('fuel', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a1', related_query_name='a2', to='main.company')),
            ],
            options={
                'default_related_name': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='QuestionAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_title', models.CharField(max_length=128)),
                ('info', models.CharField(blank=True, max_length=256, null=True)),
                ('question_type', models.CharField(choices=[('D', 'Diaria'), ('M', 'Mantenimiento')], default='D', max_length=1)),
                ('answer_type', models.CharField(choices=[('YN', 'Sí-No'), ('3S', 'Bueno-Regular-Malo'), ('NR', 'Número'), ('TX', 'Texto')], default='YN', max_length=2)),
                ('allows_observations', models.BooleanField(default=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o1', related_query_name='o2', to='main.partabsproxy')),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='n1', related_query_name='n2', to='main.questiongroup')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1', related_query_name='p2', to='main.vehicle')),
            ],
            options={
                'default_related_name': 'question_abs',
            },
        ),
        migrations.CreateModel(
            name='PartWithoutLifespan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=128, null=True)),
                ('last_changed_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_changed_km', models.PositiveIntegerField(blank=True, default=0)),
                ('functionality', models.CharField(choices=[('OK', 'OK'), ('WR', 'Atención'), ('VB', 'Muy Mala'), ('NF', 'No Funciona')], default='OK', max_length=2)),
                ('update_info', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
            options={
                'default_related_name': 'parts_without_lifespan',
            },
        ),
        migrations.CreateModel(
            name='PartWithLifespan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=128, null=True)),
                ('last_changed_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_changed_km', models.PositiveIntegerField(blank=True, default=0)),
                ('functionality', models.CharField(choices=[('OK', 'OK'), ('WR', 'Atención'), ('VB', 'Muy Mala'), ('NF', 'No Funciona')], default='OK', max_length=2)),
                ('update_info', models.BooleanField(default=True)),
                ('change_frequency_timedelta', models.DurationField(blank=True, null=True)),
                ('change_frequency_km', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
            options={
                'default_related_name': 'parts_with_lifespan',
            },
        ),
        migrations.CreateModel(
            name='PartTyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=128, null=True)),
                ('last_changed_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_changed_km', models.PositiveIntegerField(blank=True, default=0)),
                ('functionality', models.CharField(choices=[('OK', 'OK'), ('WR', 'Atención'), ('VB', 'Muy Mala'), ('NF', 'No Funciona')], default='OK', max_length=2)),
                ('update_info', models.BooleanField(default=True)),
                ('change_frequency_timedelta', models.DurationField(blank=True, null=True)),
                ('change_frequency_km', models.PositiveIntegerField(blank=True, null=True)),
                ('recaped', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
            options={
                'default_related_name': 'parts_tyre',
            },
        ),
        migrations.CreateModel(
            name='PartProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
            options={
                'default_related_name': 'parts_proxy',
            },
        ),
        migrations.CreateModel(
            name='PartFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replaced', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=True)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('done_by', models.ForeignKey(limit_choices_to={'profile__position_type': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='h1', related_query_name='h2', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i1', related_query_name='i2', to='main.partproxy')),
            ],
            options={
                'default_related_name': 'part_fixes',
            },
        ),
        migrations.CreateModel(
            name='PartChangeNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info', models.CharField(blank=True, max_length=1024, null=True)),
                ('urgency_type', models.CharField(choices=[('CR', 'Crítico'), ('IM', 'Importante'), ('EV', 'Eventual'), ('NO', 'Notificado')], default='NO', max_length=2)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f1', related_query_name='f2', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g1', related_query_name='g2', to='main.partproxy')),
            ],
            options={
                'default_related_name': 'part_change_notices',
            },
        ),
        migrations.AddField(
            model_name='formabs',
            name='form_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='j1', related_query_name='j2', to='main.formgroup'),
        ),
        migrations.AddField(
            model_name='formabs',
            name='questions_abs',
            field=models.ManyToManyField(to='main.questionabs'),
        ),
        migrations.AddField(
            model_name='formabs',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k1', related_query_name='k2', to='main.vehicle'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionabs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.questionabs')),
                ('yes_no', models.BooleanField(blank=True, default=None, null=True)),
                ('good_regular_bad', models.CharField(blank=True, choices=[('G', 'Bueno'), ('R', 'Regular'), ('B', 'Malo')], default=None, max_length=1, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r1', related_query_name='r2', to='main.form')),
                ('question_abs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q1', related_query_name='q2', to='main.questionabs')),
            ],
            options={
                'default_related_name': 'questions',
            },
            bases=('main.questionabs',),
        ),
        migrations.AddIndex(
            model_name='partproxy',
            index=models.Index(fields=['content_type', 'object_id'], name='main_partpr_content_fabeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='partabsproxy',
            index=models.Index(fields=['content_type', 'object_id'], name='main_partab_content_3b3619_idx'),
        ),
        migrations.AddField(
            model_name='form',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m1', related_query_name='m2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='form_abs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l1', related_query_name='l2', to='main.formabs'),
        ),
    ]
