# Generated by Django 4.1.7 on 2023-03-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinstace',
            name='checklist_question_instances',
            field=models.ManyToManyField(blank=True, to='main.checklistquestioninstance'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='checklist_question_templates',
            field=models.ManyToManyField(blank=True, to='main.checklistquestiontemplate'),
        ),
    ]
