# Generated by Django 4.2.1 on 2023-05-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontemplate',
            name='answer_session',
            field=models.ManyToManyField(blank=True, to='main.questionanswersession'),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='main.vehicle'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='question_answer_sessions',
            field=models.ManyToManyField(blank=True, to='main.questionanswersession'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='question_instances',
            field=models.ManyToManyField(blank=True, to='main.questioninstance'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='question_templates',
            field=models.ManyToManyField(blank=True, to='main.questiontemplate'),
        ),
    ]
