# Generated by Django 4.2 on 2023-04-13 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistquestioninstance',
            old_name='answer_checkbox',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='checklistquestioninstance',
            old_name='title',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='checklistquestiontemplate',
            old_name='title',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='checklistinstace',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='checklistinstace',
            name='checklist_question_instances',
        ),
        migrations.RemoveField(
            model_name='checklistquestioninstance',
            name='allow_notes',
        ),
        migrations.RemoveField(
            model_name='checklistquestioninstance',
            name='answer_radio_10',
        ),
        migrations.RemoveField(
            model_name='checklistquestioninstance',
            name='answer_radio_5',
        ),
        migrations.RemoveField(
            model_name='checklistquestioninstance',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='checklistquestioninstance',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='checklistquestioninstance',
            name='answer_wheel',
        ),
        migrations.RemoveField(
            model_name='checklistquestioninstance',
            name='text',
        ),
        migrations.RemoveField(
            model_name='checklistquestiontemplate',
            name='allow_notes',
        ),
        migrations.RemoveField(
            model_name='checklistquestiontemplate',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='checklistquestiontemplate',
            name='text',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='drivetrain_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='checklistinstace',
            name='completed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='checklistquestioninstance',
            name='checklist_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.checklistinstace'),
        ),
        migrations.AddField(
            model_name='checklistquestioninstance',
            name='checklist_question_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.checklistquestiontemplate'),
        ),
        migrations.AddField(
            model_name='checklistquestioninstance',
            name='info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='checklistquestiontemplate',
            name='info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='checklistquestiontemplate',
            name='periodicity_days',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='checklistquestiontemplate',
            name='periodicity_days_notice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='checklistquestiontemplate',
            name='position_type',
            field=models.SmallIntegerField(choices=[('-1', 'Not assigned'), ('1', 'Driver'), ('2', 'Mechanic'), ('3', 'Administrator'), ('4', 'Super user')], default='-1'),
        ),
        migrations.AddField(
            model_name='checklistquestiontemplate',
            name='vehicles',
            field=models.ManyToManyField(blank=True, null=True, to='main.vehicle'),
        ),
        migrations.DeleteModel(
            name='ChecklistTemplate',
        ),
    ]
