# Generated by Django 4.2.1 on 2024-01-16 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='update_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='last_changed_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='part',
            name='last_changed_km',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='partwithlifespan',
            name='change_frequency_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
