# Generated by Django 4.2.1 on 2024-01-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_part_update_info_alter_part_last_changed_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partabs',
            options={'default_related_name': 'parts_abs'},
        ),
        migrations.AlterModelOptions(
            name='parttyreabs',
            options={'default_related_name': 'parts_tyre_abs'},
        ),
        migrations.AlterModelOptions(
            name='partwithlifespanabs',
            options={'default_related_name': 'parts_with_lifespan_abs'},
        ),
        migrations.AlterModelOptions(
            name='partwithoutlifespanabs',
            options={'default_related_name': 'parts_without_lifespan_abs'},
        ),
        migrations.RemoveField(
            model_name='part',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='partabs',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='partabs',
            name='info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
