# Generated by Django 4.2 on 2023-04-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_answer_checkbox_checklistquestioninstance_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=32)),
                ('info', models.CharField(blank=True, max_length=256, null=True)),
                ('answer', models.BooleanField(default=None, null=True)),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=32)),
                ('info', models.CharField(blank=True, max_length=256, null=True)),
                ('periodicity_days', models.IntegerField(blank=True, default=0)),
                ('periodicity_anchor', models.DateField(blank=True, null=True)),
                ('periodicity_days_notice', models.IntegerField(blank=True, default=1)),
                ('position_type', models.SmallIntegerField(choices=[(0, 'Not assigned'), (1, 'Driver'), (2, 'Mechanic'), (3, 'Administrator'), (4, 'Super user')], default=0)),
                ('vehicles', models.ManyToManyField(blank=True, null=True, to='main.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='checklistquestioninstance',
            name='checklist_instance',
        ),
        migrations.RemoveField(
            model_name='checklistquestioninstance',
            name='checklist_question_template',
        ),
        migrations.RemoveField(
            model_name='checklistquestiontemplate',
            name='vehicles',
        ),
        migrations.RemoveField(
            model_name='part',
            name='part_type',
        ),
        migrations.RemoveField(
            model_name='part',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='partwheel',
            name='part_type',
        ),
        migrations.RemoveField(
            model_name='partwheel',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='part',
        ),
        migrations.RemoveField(
            model_name='repairwheel',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='repairwheel',
            name='part',
        ),
        migrations.DeleteModel(
            name='ChecklistInstace',
        ),
        migrations.DeleteModel(
            name='ChecklistQuestionInstance',
        ),
        migrations.DeleteModel(
            name='ChecklistQuestionTemplate',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='PartType',
        ),
        migrations.DeleteModel(
            name='PartWheel',
        ),
        migrations.DeleteModel(
            name='Repair',
        ),
        migrations.DeleteModel(
            name='RepairWheel',
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='checklist_question_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.questiontemplate'),
        ),
    ]
