# Generated by Django 4.2.1 on 2023-05-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_answer_session_questioninstance_answer_sessions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswersession',
            name='question_types',
        ),
        migrations.AddField(
            model_name='questionanswersession',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.questiontype'),
        ),
    ]
