# Generated by Django 4.2 on 2023-04-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questioninstance_questiontemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
