# Generated by Django 4.1.6 on 2023-02-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_checkupform_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkupquestion',
            name='answer_checkbox',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checkupquestion',
            name='answer_radio_10',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checkupquestion',
            name='answer_radio_5',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checkupquestion',
            name='answer_text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checkupquestion',
            name='answer_wheel',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='checkupquestion',
            name='template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
