# Generated by Django 4.1.6 on 2023-02-11 00:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_checkupquestion_answer_checkbox_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckupForm',
            new_name='ChecklistForm',
        ),
        migrations.RenameModel(
            old_name='CheckupQuestion',
            new_name='ChecklistQuestion',
        ),
    ]
