# Generated by Django 4.2 on 2023-04-23 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_company_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioninstance',
            old_name='checklist_question_template',
            new_name='question_template',
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='answer',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
