# Generated by Django 4.1.6 on 2023-02-11 03:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_rename_checkupform_checklistform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChecklistForm',
            new_name='Checklist',
        ),
    ]
