# Generated by Django 4.1.6 on 2023-02-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_checklistform_checklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistquestion',
            old_name='checkup_forms',
            new_name='checklists_forms',
        ),
    ]
