# Generated by Django 4.2 on 2023-04-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_questioninstance_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninstance',
            name='info',
        ),
        migrations.RemoveField(
            model_name='questioninstance',
            name='question',
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='problem_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='allow_notes',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
