# Generated by Django 4.2.1 on 2023-05-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_questionanswersession_question_instances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswersession',
            name='question_instances',
        ),
        migrations.AddField(
            model_name='questionanswersession',
            name='complete',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='answer_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_sessions', related_query_name='answer_sessions', to='main.questionanswersession'),
        ),
    ]
