# Generated by Django 4.2 on 2023-05-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_questionanswersession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswersession',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.vehicle'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='questiontemplate',
            name='answer_session',
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='answer_session',
            field=models.ManyToManyField(blank=True, null=True, to='main.questionanswersession'),
        ),
    ]
