# Generated by Django 4.2.1 on 2023-05-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_questioninstance_question_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninstance',
            name='answer_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_instances', related_query_name='question_instances', to='main.questionanswersession'),
        ),
    ]
