# Generated by Django 4.2.1 on 2023-05-26 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_alter_questioninstance_answer_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAnswerSession',
            new_name='AnswerSession',
        ),
    ]
