# Generated by Django 4.2 on 2023-05-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_questioninstance_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswersession',
            name='session_type',
            field=models.SmallIntegerField(choices=[(0, 'Generic'), (1, 'Get on'), (2, 'Get off')], default=0),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='question_type',
            field=models.SmallIntegerField(choices=[(0, 'Generic'), (1, 'Get on'), (2, 'Get off')], default=0),
        ),
    ]
