# Generated by Django 4.2.1 on 2023-06-02 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_rename_questionanswersession_answersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sessions', related_query_name='answer_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='question_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_instances', related_query_name='question_instances', to='main.questiontemplate'),
        ),
    ]
