# Generated by Django 4.2 on 2023-05-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_questionanswersession_session_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninstance',
            name='position_type',
            field=models.SmallIntegerField(choices=[(0, 'Not assigned'), (1, 'Driver'), (2, 'Mechanic'), (3, 'Administrator'), (4, 'Super user')], default=0),
        ),
    ]
