# Generated by Django 4.2 on 2023-05-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_questioninstance_position_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninstance',
            name='position_type',
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='question_type',
            field=models.SmallIntegerField(choices=[(0, 'Generic'), (1, 'Get on'), (2, 'Get off')], default=0),
        ),
    ]
