# Generated by Django 4.2 on 2023-05-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_questioninstance_position_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswersession',
            name='session_type',
            field=models.SmallIntegerField(choices=[(0, 'Generic'), (1, 'Get on'), (2, 'Get off'), (3, 'Get on & Get off')], default=0),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='question_type',
            field=models.SmallIntegerField(choices=[(0, 'Generic'), (1, 'Get on'), (2, 'Get off'), (3, 'Get on & Get off')], default=0),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='question_type',
            field=models.SmallIntegerField(choices=[(0, 'Generic'), (1, 'Get on'), (2, 'Get off'), (3, 'Get on & Get off')], default=0),
        ),
    ]
