# Generated by Django 4.1.7 on 2023-03-03 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=128, null=True)),
                ('position_type', models.SmallIntegerField(choices=[('-1', 'Not assigned'), ('1', 'Driver'), ('2', 'Mechanic'), ('3', 'Administrator'), ('4', 'Super user')], default='-1')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
