# Generated by Django 4.1.6 on 2023-02-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position_type',
            field=models.CharField(choices=[('NA', 'Not assigned'), ('DR', 'Driver'), ('MC', 'Mechanic'), ('AD', 'Administrator'), ('SU', 'Super user')], default='NA', max_length=2),
        ),
    ]
