# Generated by Django 4.2 on 2023-05-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_position_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
